#!/bin/bash
cd $OPENSHIFT_DATA_DIR  
echo -e  "<settings>\n   <localRepository>$OPENSHIFT_DATA_DIR</localRepository>\n</settings>\n" > settings.xml   
cd $OPENSHIFT_REPO_DIR/minig
mvn install -s $OPENSHIFT_DATA_DIR/settings.xml
mvn package -DskipTests
