language: java
jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8

sudo: false

before_install:
script: mvn -U -f minig/pom.xml test
after_success: 
 - echo "current branch $TRAVIS_BRANCH on jdk version $TRAVIS_JDK_VERSION"
 - if [[ $TRAVIS_JDK_VERSION == "openjdk7" ]]; then mvn -f minig/pom.xml cobertura:cobertura coveralls:cobertura; fi

