language: java
jdk:
  - oraclejdk7
  - openjdk7 

env:
  global:
     - secure: "SZKapq+Ch9o2ZXEDxf/m5ILWeoK8RladneP1TH/dW0jlFHTgqUe9P3uxFAmL2J7vpZTWCdixOUyeo/C7Av/RT2W8IYWjvgFeXTph9eQLBxjMABUe+lYfLJyngr6z4mUTRkx0/Yd+Y1OWaHXd7yk/N/xcOSOXqNze4fdroaQ1Gqw="
     - secure: "ZG9oOutajiG7HvA2DkSXoAYCRrBh8AwXqtlqS+r5oGi8ezczNgvomN3gA46CT3xtBE2ooRN4Bd8fabYdwhdlDka6xTpIUtnwq0tjHH1bZRNXtNtgYcj5qG92tb0XFOjG9DI8PnCt8MMDerbvnJJ49dDZUVnK8nT4HP4Pnn02zQ4="

script: mvn -f minig/pom.xml test
after_success: 
 - echo "current branch $TRAVIS_BRANCH on jdk version $TRAVIS_JDK_VERSION"
 - if [[ $TRAVIS_JDK_VERSION == "openjdk7" ]]; then mvn -f minig/pom.xml cobertura:cobertura coveralls:cobertura -DskipTests; fi
 - if [[ $TRAVIS_BRANCH == "master" && $TRAVIS_JDK_VERSION == "openjdk7" ]]; mvn -f minig/pom.xml package -DskipTests; then echo "deploying artefact"; curl -X PUT -T minig/target/minig.war -u travis:$PW --insecure "https://$DEPLOY_HOST/manager/deploy?update=true&path=/minig"; echo "deploy result: $?"; fi
