language: java
jdk:
  - oraclejdk7
  - openjdk7 

env:
  global:
     - secure: "SZKapq+Ch9o2ZXEDxf/m5ILWeoK8RladneP1TH/dW0jlFHTgqUe9P3uxFAmL2J7vpZTWCdixOUyeo/C7Av/RT2W8IYWjvgFeXTph9eQLBxjMABUe+lYfLJyngr6z4mUTRkx0/Yd+Y1OWaHXd7yk/N/xcOSOXqNze4fdroaQ1Gqw="
     - secure: "ZG9oOutajiG7HvA2DkSXoAYCRrBh8AwXqtlqS+r5oGi8ezczNgvomN3gA46CT3xtBE2ooRN4Bd8fabYdwhdlDka6xTpIUtnwq0tjHH1bZRNXtNtgYcj5qG92tb0XFOjG9DI8PnCt8MMDerbvnJJ49dDZUVnK8nT4HP4Pnn02zQ4="

before_install:
 - sudo apt-get install nodejs npm
 - npm install karma phantomjs
 - npm install karma-junit-reporter --save-dev
 - npm install karma-ng-json2js-preprocessor --save-dev
 - npm install karma-ng-scenario --save-dev
 - npm install karma-ng-html2js-preprocessor --save-dev
 - export PATH=$PATH:~/.nvm/v0.10.22/lib/node_modules/karma
script: mvn -f minig/pom.xml test
after_success: 
 - mvn -f minig/pom.xml cobertura:cobertura coveralls:cobertura

 - if [[ $TRAVIS_BRANCH == "master" && $TRAVIS_JDK_VERSION == "openjdk7" ]]; then mvn -f minig/pom.xml package; curl -X PUT -T minig/target/minig.war -u travis:$PW --insecure "https://$DEPLOY_HOST/manager/deploy?update=true&path=/minig" > /dev/null 2>&1; fi
